// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJhwA1uRtBz3Ed1dXRfB9YdHgV4JzveF4',
    appId: '1:284088359614:web:fd017aa6f2afd31a3adcef',
    messagingSenderId: '284088359614',
    projectId: 'home-care-4a95e',
    authDomain: 'home-care-4a95e.firebaseapp.com',
    storageBucket: 'home-care-4a95e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWQk9LOPYHGKZ4X_6gqDyVRSbmnxGicA4',
    appId: '1:284088359614:android:d2429c8670c911b03adcef',
    messagingSenderId: '284088359614',
    projectId: 'home-care-4a95e',
    storageBucket: 'home-care-4a95e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCurJ1oAP4Q3R9zS_8CtrJGIWDDRZgZ5vk',
    appId: '1:284088359614:ios:9a8f3928f154425c3adcef',
    messagingSenderId: '284088359614',
    projectId: 'home-care-4a95e',
    storageBucket: 'home-care-4a95e.firebasestorage.app',
    iosClientId: '284088359614-qrssh7fivct14js7i7jsetoce83hu2eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeCare',
  );
}
